<?php

namespace App\Services\Security\Schnorr;

/**
 * Reference: crypto_design.md §4.4.2 (Global Parameters)
 *
 * Immutable holder for the server-wide Schnorr group:
 *  - p: large prime modulus
 *  - q: prime order of the subgroup generated by alpha (q | p-1)
 *  - alpha: generator of the order-q subgroup of (Z/pZ)*
 *
 * All values are stored as decimal strings (arbitrary precision,
 * GMP-compatible) rather than native ints, since p/q are far larger
 * than PHP_INT_MAX.
 */
final class SchnorrParameters
{
    public function __construct(
        public readonly string $p,
        public readonly string $q,
        public readonly string $alpha,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self($data['p'], $data['q'], $data['alpha']);
    }

    public function toArray(): array
    {
        return ['p' => $this->p, 'q' => $this->q, 'alpha' => $this->alpha];
    }
}
