<?php

namespace App\Services\Security\KeyManagement;

use App\Exceptions\Crypto\InvalidPublicKeyException;
use App\Models\PublicKey;
use App\Models\User;
use App\Repositories\Contracts\PublicKeyRepositoryInterface;
use App\Services\Security\Schnorr\SchnorrParameterProviderInterface;

/**
 * Reference: testing_spec.md §7.4 (KeyManagerService)
 *
 * Validates PUBLIC key material before delegating storage to
 * PublicKeyRepositoryInterface. Private keys are never accepted by
 * this service (FR-009).
 */
class KeyManagerService implements KeyManagerServiceInterface
{
    /** X25519 public keys are always exactly 32 bytes. */
    private const ECC_PUBLIC_KEY_BYTES = 32;

    public function __construct(
        private readonly PublicKeyRepositoryInterface $publicKeys,
        private readonly SchnorrParameterProviderInterface $schnorrParameters,
    ) {}

    public function uploadPublicKeys(User $user, string $eccPublicKeyB64, string $schnorrPublicKeyDecimal): PublicKey
    {
        $this->validateEccPublicKey($eccPublicKeyB64);
        $this->validateSchnorrPublicKey($schnorrPublicKeyDecimal);

        return $this->publicKeys->upsert($user, $eccPublicKeyB64, $schnorrPublicKeyDecimal);
    }

    public function getPublicKeys(User $user): ?PublicKey
    {
        return $this->publicKeys->forUser($user);
    }

    /**
     * Confirms the value is well-formed base64 decoding to exactly
     * 32 bytes. This is a FORMAT check only — it cannot confirm the
     * bytes represent a valid/safe X25519 point (X25519 famously
     * accepts any 32-byte string as input), which is an accepted
     * limitation of the curve, not something this service can fix.
     */
    private function validateEccPublicKey(string $eccPublicKeyB64): void
    {
        $decoded = base64_decode($eccPublicKeyB64, true);

        if ($decoded === false || strlen($decoded) !== self::ECC_PUBLIC_KEY_BYTES) {
            throw new InvalidPublicKeyException(
                'kunci publik ECC harus dalam format base64 dan tepat berukuran 32 byte (X25519).'
            );
        }
    }

    /**
     * Confirms the value is a decimal integer y satisfying
     * 1 < y < p, and that y actually lies in the order-q subgroup
     * generated by alpha (y^q mod p == 1) — catching keys that were
     * corrupted, truncated, or generated against a different/older
     * parameter set entirely, before they can cause confusing
     * downstream signature-verification failures.
     */
    private function validateSchnorrPublicKey(string $schnorrPublicKeyDecimal): void
    {
        if (! preg_match('/^[0-9]+$/', $schnorrPublicKeyDecimal)) {
            throw new InvalidPublicKeyException('kunci publik Schnorr harus berupa string bilangan bulat desimal.');
        }

        $params = $this->schnorrParameters->current();
        $p = gmp_init($params->p, 10);
        $q = gmp_init($params->q, 10);
        $y = gmp_init($schnorrPublicKeyDecimal, 10);

        if (gmp_cmp($y, 1) <= 0 || gmp_cmp($y, $p) >= 0) {
            throw new InvalidPublicKeyException('kunci publik Schnorr berada di luar rentang untuk parameter saat ini.');
        }

        if (gmp_cmp(gmp_powm($y, $q, $p), 1) !== 0) {
            throw new InvalidPublicKeyException('kunci publik Schnorr tidak termasuk dalam subgrup yang diharapkan.');
        }
    }
}
